version: '3'
volumes:
  db:
services:
  ${serviceName}:
    container_name: ${serviceName}
    image: ${strapiImage}
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=${serviceName}
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_AUTHENTICATION_DATABASE=${serviceName}
    ports:
      - 1337:1337
    volumes:
      - ./../code_redeemer_be:/usr/src/api/strapi-app
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${serviceName}
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    restart: always